DROP TABLE IF EXISTS Languages CASCADE;

DROP TABLE IF EXISTS Translations CASCADE;
DROP TABLE IF EXISTS TranslationInfo CASCADE;
DROP TABLE IF EXISTS TranslationRelationships CASCADE;

DROP TABLE IF EXISTS Users CASCADE;
DROP TABLE IF EXISTS Sources CASCADE;
DROP TABLE IF EXISTS Files CASCADE;
DROP TABLE IF EXISTS Styles CASCADE;
DROP TABLE IF EXISTS Properties CASCADE;

DROP TABLE IF EXISTS Books CASCADE;
DROP TABLE IF EXISTS BookToFile CASCADE;
DROP TABLE IF EXISTS BookGroups CASCADE;
DROP TABLE IF EXISTS BookToGroup CASCADE;
DROP TABLE IF EXISTS BookGroupNames CASCADE;

DROP TABLE IF EXISTS Chapters CASCADE;
DROP TABLE IF EXISTS ChapterOccurences CASCADE;

DROP TABLE IF EXISTS Paragraphs CASCADE;
DROP TABLE IF EXISTS Verses CASCADE;
DROP TABLE IF EXISTS VerseOccurences CASCADE;
DROP TABLE IF EXISTS VersesToParagraphs CASCADE;
DROP TABLE IF EXISTS ExcludedVerses CASCADE;

DROP TABLE IF EXISTS TranslationFootNotes CASCADE;
DROP TABLE IF EXISTS TranslationRefNotes CASCADE;

DROP TABLE IF EXISTS Strongs CASCADE;
DROP TABLE IF EXISTS Entities CASCADE;

DROP TABLE IF EXISTS Occurences CASCADE;
DROP TABLE IF EXISTS Quotes CASCADE;
DROP TABLE IF EXISTS EntityOccurence CASCADE;
DROP TABLE IF EXISTS StrongsOccurence CASCADE;

DROP TABLE IF EXISTS Tokens CASCADE;

DROP TABLE IF EXISTS UserNotes CASCADE;
DROP TABLE IF EXISTS NoteRelationships CASCADE;
DROP TABLE IF EXISTS UserHighlightsAnchors CASCADE;
DROP TABLE IF EXISTS UserHighlights CASCADE;
DROP TABLE IF EXISTS ReadHistory CASCADE;

DROP TABLE IF EXISTS Locations CASCADE;
DROP TABLE IF EXISTS LocationOccurence CASCADE;
DROP TABLE IF EXISTS LocationRelationships CASCADE;
DROP TABLE IF EXISTS GeoSources CASCADE;
DROP TABLE IF EXISTS LocationDataSources CASCADE;
DROP TABLE IF EXISTS Images CASCADE;
DROP TABLE IF EXISTS LocationImages CASCADE;
DROP TABLE IF EXISTS Geometries CASCADE;
DROP TABLE IF EXISTS LocationGeometry CASCADE;

DROP TABLE IF EXISTS Harmonies CASCADE;
DROP TABLE IF EXISTS HarmonyMapping CASCADE;
DROP TABLE IF EXISTS ChronologyOccurence CASCADE;
DROP TABLE IF EXISTS Chronology CASCADE;
