services:
  db:
    image: postgis/postgis
    restart: always
    ports: 
      - "5444:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: postgres # default database
    volumes:
      - pg_data:/var/lib/postgresql/data
volumes:
  pg_data: